# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49d5d088cbc9ff2acab5c7a2ca871e2c96fb03aaa4191ebaaf6c22143b4a4ff4aca7f67d8e8e0f5f7678cc94c149643ffb2725af4cd5f21f81e3372c76754f5c

test:
  secret_key_base: 62fb237a4a4e320c62f65b7810ff24a166928b59d79cb11c7631c91272a3cee85bbfa89a42c26e084f1eb69ffa4411ba7509875aaa129ffc1a121a0c4b724806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
